# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 499515828fa2bfdf9e3b999040a3a512fd91d76049f5df42b10028827b55da68c854df63121c540c8208950e117f95967d48fad38b6d975d1413c2e62efd1d38

test:
  secret_key_base: 2350e05ea4b1ee3330de11a5ec828738d18235b2c423d41b9807f5415822f29f4df0faaf633afda36d058cadbc80cc245b255ea386b86735573c439f20ddbddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
